In [7]:
import numpy as np
import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense, Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import *
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt
%matplotlib inline

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import shuffle

Using TensorFlow backend.


In [8]:
filepath_files = '/Users/krahman/work/tutorials/tensorflow_classification/data/'

train_samples = pd.read_csv(filepath_files + 'mod_x_train.csv').drop('Unnamed: 0', axis=1)
train_labels = pd.read_csv(filepath_files + 'mod_y_train.csv').drop('Unnamed: 0', axis=1)
test_samples = pd.read_csv(filepath_files + 'mod_x_test.csv').drop('Unnamed: 0', axis=1)
test_labels = pd.read_csv(filepath_files + 'mod_y_test.csv').drop('470624', axis=1)
test_labels = test_labels.rename(columns={"0":"isFraud"})

test_samples = pd.concat([test_samples, test_labels], axis=1)
test_samples, val_samples = train_test_split(test_samples, test_size=.2)

In [9]:
train_labels = train_labels
test_labels = test_samples.pop('isFraud')
val_labels = val_samples.pop('isFraud')

In [10]:
train_labels = np.array(train_labels)
test_labels = np.array(test_labels.fillna(0).astype(int))
val_labels = np.array(val_labels)

train_samples = np.array(train_samples)
test_samples = np.array(test_samples)
val_samples = np.array(val_samples)

In [11]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples)#.reshape(-1,1))
scaled_test_samples = scaler.fit_transform(test_samples)#.reshape(-1,1))
scaled_val_samples = scaler.fit_transform(val_samples)#.reshape(-1,1))

In [ ]:
#####################

In [27]:
model = Sequential([
    Dense(4096, input_shape=(233,), activation='relu'),
    Dense(64, activation='relu'),
    Dense(2, activation='softmax')
])
model.compile(Adam(lr=.001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=10, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)

In [38]:
from keras import losses

In [ ]:
# testing .00001 
# best 4096, 64, batch=10 lr=.0001
model2 = Sequential([
    Dense(4096, input_shape=(233,), activation='relu'),
    Dense(64, activation='relu'),
    Dense(2, activation='softmax')
])
model2.compile(Adam(lr=.00001), loss=losses.sparse_categorical_crossentropy, metrics=['accuracy'])
model2.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=15, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)



In [ ]:
# testing .0001 
# best 4096, 64, batch=10 lr=.0001
model2 = Sequential([
    Dense(4096, input_shape=(233,), activation='relu'),
    Dense(64, activation='relu'),
    Dense(2, activation='softmax')
])
model2.compile(Adam(lr=.0001), loss=losses.sparse_categorical_crossentropy, metrics=['accuracy'])
model2.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=15, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)



In [76]:
# testing lr=.00001
model3 = Sequential([
    Dense(4096, input_shape=(233,), activation='relu'),
    Dense(64, activation='relu'),
    Dense(2, activation='softmax')
])
model3.compile(Adam(lr=.00001), loss=losses.sparse_categorical_crossentropy, metrics=['accuracy'])
model3.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=15, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)



Train on 190000 samples, validate on 11811 samples
Epoch 1/15
 - 321s - loss: 0.3992 - accuracy: 0.8250 - val_loss: 0.6065 - val_accuracy: 0.7405
Epoch 2/15
 - 321s - loss: 0.2876 - accuracy: 0.8835 - val_loss: 0.6200 - val_accuracy: 0.7806
Epoch 3/15
 - 321s - loss: 0.2524 - accuracy: 0.8997 - val_loss: 0.5328 - val_accuracy: 0.8472
Epoch 4/15
 - 321s - loss: 0.2338 - accuracy: 0.9080 - val_loss: 0.5947 - val_accuracy: 0.8381
Epoch 5/15
 - 323s - loss: 0.2218 - accuracy: 0.9127 - val_loss: 0.5674 - val_accuracy: 0.8559
Epoch 6/15
 - 320s - loss: 0.2130 - accuracy: 0.9163 - val_loss: 0.5867 - val_accuracy: 0.8567
Epoch 7/15
 - 321s - loss: 0.2056 - accuracy: 0.9193 - val_loss: 0.5353 - val_accuracy: 0.8733
Epoch 8/15
 - 322s - loss: 0.1995 - accuracy: 0.9226 - val_loss: 0.5687 - val_accuracy: 0.8657
Epoch 9/15
 - 321s - loss: 0.1941 - accuracy: 0.9243 - val_loss: 0.5238 - val_accuracy: 0.8829
Epoch 10/15
 - 321s - loss: 0.1890 - accuracy: 0.9275 - val_loss: 0.5222 - val_accuracy: 0.885

In [57]:
# testing epochs=15 
model3 = Sequential([
    Dense(4096, input_shape=(233,), activation='relu'),
    Dense(64, activation='relu'),
    Dense(2, activation='softmax')
])
model3.compile(Adam(lr=.0001), loss=losses.sparse_categorical_crossentropy, metrics=['accuracy'])
model3.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=15, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)



Train on 190000 samples, validate on 11811 samples
Epoch 1/15
 - 317s - loss: 0.3013 - accuracy: 0.8706 - val_loss: 0.5817 - val_accuracy: 0.8201
Epoch 2/15
 - 320s - loss: 0.2361 - accuracy: 0.9040 - val_loss: 0.8494 - val_accuracy: 0.7330
Epoch 3/15
 - 321s - loss: 0.2172 - accuracy: 0.9126 - val_loss: 0.5897 - val_accuracy: 0.8395
Epoch 4/15
 - 322s - loss: 0.2035 - accuracy: 0.9185 - val_loss: 0.6941 - val_accuracy: 0.7921
Epoch 5/15
 - 323s - loss: 0.1939 - accuracy: 0.9234 - val_loss: 0.8733 - val_accuracy: 0.7179
Epoch 6/15
 - 323s - loss: 0.1863 - accuracy: 0.9267 - val_loss: 0.7315 - val_accuracy: 0.7997
Epoch 7/15
 - 322s - loss: 0.1801 - accuracy: 0.9291 - val_loss: 0.6606 - val_accuracy: 0.8119
Epoch 8/15
 - 323s - loss: 0.1746 - accuracy: 0.9321 - val_loss: 0.5967 - val_accuracy: 0.8418
Epoch 9/15
 - 322s - loss: 0.1687 - accuracy: 0.9346 - val_loss: 0.5432 - val_accuracy: 0.8443
Epoch 10/15
 - 325s - loss: 0.1653 - accuracy: 0.9354 - val_loss: 0.6724 - val_accuracy: 0.785

In [ ]:
# testing .00001
model3 = Sequential([
    Dense(128, input_shape=(233,), activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(2, activation='softmax')
])
model3.compile(Adam(lr=.00001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model3.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=15, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)

Train on 190000 samples, validate on 11811 samples
Epoch 1/15
 - 165s - loss: 0.4128 - accuracy: 0.8135 - val_loss: 0.3503 - val_accuracy: 0.8836
Epoch 2/15
 - 145s - loss: 0.3033 - accuracy: 0.8710 - val_loss: 0.4259 - val_accuracy: 0.8683
Epoch 3/15
 - 135s - loss: 0.2738 - accuracy: 0.8867 - val_loss: 0.4524 - val_accuracy: 0.8655
Epoch 4/15
 - 136s - loss: 0.2579 - accuracy: 0.8946 - val_loss: 0.4884 - val_accuracy: 0.8678
Epoch 5/15
 - 139s - loss: 0.2475 - accuracy: 0.8993 - val_loss: 0.4599 - val_accuracy: 0.8782
Epoch 6/15
 - 143s - loss: 0.2395 - accuracy: 0.9038 - val_loss: 0.5160 - val_accuracy: 0.8651
Epoch 7/15


In [ ]:
# testing
model3 = Sequential([
    Dense(128, input_shape=(233,), activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(2, activation='softmax')
])
model3.compile(Adam(lr=.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model3.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=15, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)

In [ ]:
# testing .00001
model3 = Sequential([
    Dense(512, input_shape=(233,), activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(2, activation='softmax')
])
model3.compile(Adam(lr=.00001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model3.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=15, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)

In [ ]:
# testing .0001
model3 = Sequential([
    Dense(512, input_shape=(233,), activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(512, activation='relu'),
    Dense(2, activation='softmax')
])
model3.compile(Adam(lr=.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model3.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=15, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)

In [75]:
# testing
model3 = Sequential([
    Dense(256, input_shape=(233,), activation='relu'),
    Dense(256, activation='relu'),
    Dense(256, activation='relu'),
    Dense(256, activation='relu'),
    Dense(256, activation='relu'),
    Dense(256, activation='relu'),
    Dense(256, activation='relu'),
    Dense(256, activation='relu'),
    Dense(2, activation='softmax')
])
model3.compile(Adam(lr=.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model3.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=15, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)

Train on 190000 samples, validate on 11811 samples
Epoch 1/15
 - 217s - loss: 0.3056 - accuracy: 0.8685 - val_loss: 0.3789 - val_accuracy: 0.9004
Epoch 2/15
 - 215s - loss: 0.2416 - accuracy: 0.9009 - val_loss: 0.4035 - val_accuracy: 0.8996
Epoch 3/15
 - 215s - loss: 0.2200 - accuracy: 0.9112 - val_loss: 0.4145 - val_accuracy: 0.8894
Epoch 4/15
 - 215s - loss: 0.2051 - accuracy: 0.9178 - val_loss: 0.4427 - val_accuracy: 0.8854
Epoch 5/15
 - 235s - loss: 0.1941 - accuracy: 0.9224 - val_loss: 0.4560 - val_accuracy: 0.8824
Epoch 6/15
 - 215s - loss: 0.1839 - accuracy: 0.9267 - val_loss: 0.5035 - val_accuracy: 0.8733
Epoch 7/15
 - 215s - loss: 0.1762 - accuracy: 0.9307 - val_loss: 0.5650 - val_accuracy: 0.8870
Epoch 8/15
 - 216s - loss: 0.1690 - accuracy: 0.9343 - val_loss: 0.7868 - val_accuracy: 0.8779
Epoch 9/15
 - 215s - loss: 0.1631 - accuracy: 0.9365 - val_loss: 0.7460 - val_accuracy: 0.8504
Epoch 10/15
 - 216s - loss: 0.1577 - accuracy: 0.9385 - val_loss: 0.8295 - val_accuracy: 0.838

In [ ]:
# Testing .00001
model3 = Sequential([
    Dense(256, input_shape=(233,), activation='relu'),
    Dense(256, activation='relu'),
    Dense(256, activation='relu'),
    Dense(256, activation='relu'),
    Dense(256, activation='relu'),
    Dense(2, activation='softmax')
])
model3.compile(Adam(lr=.00001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model3.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=15, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)

In [72]:
# BEST
model3 = Sequential([
    Dense(256, input_shape=(233,), activation='relu'),
    Dense(256, activation='relu'),
    Dense(256, activation='relu'),
    Dense(256, activation='relu'),
    Dense(256, activation='relu'),
    Dense(2, activation='softmax')
])
model3.compile(Adam(lr=.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model3.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=15, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)

Train on 190000 samples, validate on 11811 samples
Epoch 1/15
 - 153s - loss: 0.3042 - accuracy: 0.8687 - val_loss: 0.4330 - val_accuracy: 0.8751
Epoch 2/15
 - 151s - loss: 0.2425 - accuracy: 0.9009 - val_loss: 0.4721 - val_accuracy: 0.8524
Epoch 3/15
 - 151s - loss: 0.2201 - accuracy: 0.9107 - val_loss: 0.4384 - val_accuracy: 0.8772
Epoch 4/15
 - 150s - loss: 0.2046 - accuracy: 0.9182 - val_loss: 0.4329 - val_accuracy: 0.8684
Epoch 5/15
 - 151s - loss: 0.1935 - accuracy: 0.9229 - val_loss: 0.5213 - val_accuracy: 0.8418
Epoch 6/15
 - 150s - loss: 0.1842 - accuracy: 0.9269 - val_loss: 0.3829 - val_accuracy: 0.9070
Epoch 7/15
 - 150s - loss: 0.1754 - accuracy: 0.9309 - val_loss: 0.6673 - val_accuracy: 0.8062
Epoch 8/15
 - 150s - loss: 0.1681 - accuracy: 0.9342 - val_loss: 0.5271 - val_accuracy: 0.8724
Epoch 9/15
 - 152s - loss: 0.1615 - accuracy: 0.9371 - val_loss: 0.5224 - val_accuracy: 0.8867
Epoch 10/15
 - 151s - loss: 0.1570 - accuracy: 0.9393 - val_loss: 0.7257 - val_accuracy: 0.835

In [ ]:
# testing .00001
model2 = Sequential([
    Dense(64, input_shape=(233,), activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(2, activation='softmax')
])
model2.compile(Adam(lr=.00001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model2.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=15, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)

In [74]:
# testing 
model2 = Sequential([
    Dense(64, input_shape=(233,), activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(2, activation='softmax')
])
model2.compile(Adam(lr=.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model2.fit(scaled_train_samples, train_labels, validation_data=(scaled_val_samples, val_labels), 
          batch_size=10, epochs=15, shuffle=True, verbose=2, workers=8, use_multiprocessing=True)

Train on 190000 samples, validate on 11811 samples
Epoch 1/15
 - 109s - loss: 0.3394 - accuracy: 0.8516 - val_loss: 0.4081 - val_accuracy: 0.8672
Epoch 2/15
 - 103s - loss: 0.2667 - accuracy: 0.8897 - val_loss: 0.3416 - val_accuracy: 0.8987
Epoch 3/15
 - 94s - loss: 0.2460 - accuracy: 0.8999 - val_loss: 0.6763 - val_accuracy: 0.7746
Epoch 4/15
 - 93s - loss: 0.2336 - accuracy: 0.9058 - val_loss: 0.4247 - val_accuracy: 0.8811
Epoch 5/15
 - 95s - loss: 0.2242 - accuracy: 0.9100 - val_loss: 0.6480 - val_accuracy: 0.8294
Epoch 6/15
 - 93s - loss: 0.2177 - accuracy: 0.9127 - val_loss: 0.5598 - val_accuracy: 0.8297
Epoch 7/15
 - 93s - loss: 0.2111 - accuracy: 0.9161 - val_loss: 0.5606 - val_accuracy: 0.8475
Epoch 8/15
 - 93s - loss: 0.2053 - accuracy: 0.9183 - val_loss: 0.6970 - val_accuracy: 0.8059
Epoch 9/15
 - 92s - loss: 0.2008 - accuracy: 0.9207 - val_loss: 0.6206 - val_accuracy: 0.8248
Epoch 10/15
 - 93s - loss: 0.1970 - accuracy: 0.9221 - val_loss: 0.7241 - val_accuracy: 0.7805
Epoch 

In [59]:
predictions = model.predict(scaled_test_samples, batch_size=10, verbose=0)
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=0)
cm = confusion_matrix(test_labels, rounded_predictions)
cm

array([[41507,  4011],
       [ 1583,   142]])

In [445]:
predictions = model.predict(scaled_test_samples, batch_size=10, verbose=0)
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=0)
cm = confusion_matrix(test_labels, rounded_predictions)
cm

array([[42957,  2593],
       [ 1582,   111]])

In [215]:
predictions = model.predict(scaled_test_samples, batch_size=100, verbose=0)
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=0)
cm = confusion_matrix(test_labels, rounded_predictions)
cm #dense 32

array([[72729,   206],
       [ 2246,   407]])

In [213]:
predictions = model.predict(scaled_test_samples, batch_size=100, verbose=0)
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=0)
cm = confusion_matrix(test_labels, rounded_predictions)
cm #batch 100

array([[72697,   238],
       [ 2219,   434]])

In [211]:
predictions = model.predict(scaled_test_samples, batch_size=100, verbose=0)
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=0)
cm = confusion_matrix(test_labels, rounded_predictions)
cm #1 dense layer

array([[72664,   271],
       [ 2192,   461]])

In [209]:
predictions = model.predict(scaled_test_samples, batch_size=100, verbose=0)
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=0)
cm = confusion_matrix(test_labels, rounded_predictions)
cm #batch_size=50

array([[72585,   350],
       [ 2054,   599]])

In [207]:
predictions = model.predict(scaled_test_samples, batch_size=100, verbose=0)
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=0)
cm = confusion_matrix(test_labels, rounded_predictions)
cm

array([[72666,   269],
       [ 2147,   506]])

In [205]:
predictions = model.predict(scaled_test_samples, batch_size=100, verbose=0)
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=0)
cm = confusion_matrix(test_labels, rounded_predictions)
cm # lr=.0001

array([[72744,   191],
       [ 2272,   381]])

In [203]:
predictions = model.predict(scaled_test_samples, batch_size=100, verbose=0)
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=0)
cm = confusion_matrix(test_labels, rounded_predictions)
cm # lr=.001

array([[72438,   497],
       [ 1901,   752]])

In [ ]:
### EXAMPLE CODE ####
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

model = Sequential([
    Dense(16, input_shape=(1,), activation='relu'),
    Dense(32, activation='relu'),
    Dense(2, activation='softmax')
])

model.compile(Adam(lr=.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(scaled_train_samples, train_labels, validation_split=0.1, batch_size=5, epochs=20, shuffle=True, verbose=2, workers=4)

###
test_labels = np.array(test_labels)
test_samples = np.array(test_samples)

scaler = MinMaxScaler(feature_range=(0,1))
scaled_test_samples = scaler.fit_transform((test_samples).reshape(-1,1))

predictions = model.predict(scaled_test_samples, batch_size=10, verbose=0)
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=0)

###
cm = confusion_matrix(test_labels, rounded_predictions)

In [ ]:
# shuffle full dataset first
# then split dataset for train, test, valid
# pop off fraud for each data set 
# apply MinMaxScaler to training set 

In [ ]:
# model = Sequential([
#     Dense(16, input_shape=(1,), activation='relu'),
#     Dense(32, activation='relu'),
#     Dense(2, activation='softmax')
# ])

In [ ]:
model = Sequential([
    Dense(16, input_shape())
    
])